[output]
# If disabled, the path in presets are directly applied, relative or absolute
# If enabled, the paths in presets must be relative
use-root = true
# Can be relative or absolute
out-root = "out"
# whether to make file links or make full copies
make-links = true

[features]
# Needs mp3gain installed and accessible via the path
# More info in README
activated = ["mp3gain"]

[features.mp3gain]
# Runs mp3 gain on all files from a preset, it averages the gain over all files for a smoother experience.
# Warning: It can take a long time !
# Modes are "per-preset" | "on-all"
# Per-preset needs to have a boolean on each preset to know if mp3gain is ran
# On-all just bypasses the boolean, doesn't check for its existence, activates mp3gain for all
mode = "per-preset"
# Whether to juste add a tag giving the gain information or change it directly
# Options are "gain" | "tag"
# Gain actually changes the gain of the file, it modifies the file's gain!
# Tag just writes a tag giving the gain information, doesn't modify the file's audio
type = "gain"

# include-type | exclude-type
# modes are "and" | "or" defaults to "or"
# what mode to use for include/exclude flags

[[Presets]]
name = "Main"
group = "original_sort"
include-flags = ["duet", "evil", "neuro", "mashup"]
exclude-flags = ["arg", "duplicate", "v1", "v2", "encore", "unused"]
# From root
path = "main"
mp3gain = false

[[Presets]]
name = "Old"
group = "original_sort"
include-flags = ["v1", "v2"]
exclude-flags = ["arg", "duplicate", "encore", "unused"]
# From root
path = "v1v2"
mp3gain = false

[[Presets]]
name = "Duplicates v3"
group = "original_sort"
include-flags = ["duplicate"]
exclude-flags = ["arg", "v1", "v2", "encore", "unused"]
# From root
path = "duplicates/v3"
mp3gain = false

[[Presets]]
name = "Duplicates v1-v2"
group = "original_sort"
include-flags = ["duplicate"]
exclude-flags = ["arg", "v3", "encore", "unused"]
# From root
path = "duplicates"
mp3gain = false

[[Presets]]
name = "ARG"
group = "original_sort"
include-flags = ["arg"]
exclude-flags = []
#from root
path = "arg"
mp3gain = false

[[Presets]]
name = "ENCORE"
group = "original_sort"
include-flags = ["encore"]
exclude-flags = []
path = "encore"
mp3gain = false

[[Presets]]
name = "Unused"
group = "original_sort"
include-flags = ["unused"]
exclude-flags = []
path = "unused"
mp3gain = false


# Other examples of presets
#[[Presets]]
#name = "All" # Excluding ARG
#include-flags = ["evil", "neuro"]
#exclude-flags = ["encore"]
#path = "all"
#mp3gain = false

#[[Presets]]
#name = "All_encore" # Excluding ARG
#include-flags = ["encore"]
#exclude-flags = []
#path = "all_encore"
#mp3gain = false

# Zhe_Vlach_Varon's Sort

[[Presets]]
name = "subathon mashups"
group = "zvv_sort"
include-flags = ["mashup"]
exclude-flags = []
path = "subathon_mashups"
mp3gain = false

[[Presets]]
name = "v1 voice"
group = "zvv_sort"
include-flags = ["v1"]
exclude-flags = ["duplicate", "collab", "quarantine", "zvv_quarantine", "christmas", "halloween", "unused"]
path = "v1_voice"
mp3gain = false

[[Presets]]
name = "v2 voice"
group = "zvv_sort"
include-flags = ["v2"]
exclude-flags = ["duplicate", "collab", "quarantine", "zvv_quarantine", "unused"]
path = "v2_voice"
mp3gain = false

[[Presets]]
#v3 neuro only
name = "Neuro"
group = "zvv_sort"
include-flags = ["neuro"]
exclude-flags = ["duet", "evil", "v1", "v2", "duplicate", "collab", "christmas", "halloween", "originals", "official", "quarantine", "zvv_quarantine", "unused"]
path = "Neuro"
mp3gain = false

[[Presets]]
name = "Evil"
group = "zvv_sort"
include-flags = ["evil"]
exclude-flags = ["duet", "neuro", "v1", "v2", "duplicate", "collab", "christmas", "halloween", "originals", "official", "quarantine", "zvv_quarantine", "unused"]
path = "Evil"
mp3gain = false

[[Presets]]
name = "Duets Neuro Lead"
group = "zvv_sort"
include-flags = ["duet", "neuro"]
exclude-flags = ["duplicate", "collab", "christmas", "halloween", "originals", "official", "quarantine", "zvv_quarantine", "unused", "mashup"]
path = "Duets_Neuro_Lead"
mp3gain = false
include-type = "and"

[[Presets]]
name = "Duets Neuro Lead"
group = "zvv_sort"
include-flags = ["duet", "evil"]
exclude-flags = ["duplicate", "collab", "christmas", "halloween", "originals", "official", "quarantine", "zvv_quarantine", "unused", "mashup"]
path = "Duets_Evil_Lead"
mp3gain = false
include-type = "and"

[[Presets]]
name = "Twin Duet Streams"
group = "zvv_sort"
include-flags = ["duet"]
exclude-flags = ["neuro", "evil", "duplicate", "christmas", "halloween", "originals", "official", "quarantine", "zvv_quarantine", "unused", "mashup"]
path = "Duets_Twins"
mp3gain = false

[[Presets]]
name = "Neuro Originals"
group = "zvv_sort"
include-flags = ["originals", "neuro"]
exclude-flags = ["duplicate"]
path = "Neuro_Originals"
mp3gain = false
include-type = "and"

[[Presets]]
name = "Evil Originals"
group = "zvv_sort"
include-flags = ["originals", "evil"]
exclude-flags = ["duplicate"]
path = "Evil_Originals"
mp3gain = false
include-type = "and"

[[Presets]]
name = "Duet Originals"
group = "zvv_sort"
include-flags = ["originals", "duet"]
exclude-flags = ["duplicate"]
path = "Duet_Originals"
mp3gain = false
include-type = "and"

[[Presets]]
name = "Collab Covers"
group = "zvv_sort"
include-flags = ["collab"]
exclude-flags = ["official", "quarantine", "zvv_quarantine", "christmas", "halloween"]
path = "Collab_Covers"
mp3gain = false

[[Presets]]
name = "Official Covers"
group = "zvv_sort"
include-flags = ["official"]
exclude-flags = []
path = "Official_Covers"
mp3gain = false

[[Presets]]
name = "ZVV Duplicates v3 Neuro"
group = "zvv_sort"
include-flags = ["duplicate", "neuro", "v3"]
exclude-flags = ["arg", "v1", "v2", "duet", "evil", "christmas", "halloween", "quarantine", "zvv_quarantine"]
path = "Duplicates_v3_Neuro"
mp3gain = false
include-type = "and"

[[Presets]]
name = "ZVV Duplicates v3 Evil"
group = "zvv_sort"
include-flags = ["duplicate", "evil", "v3"]
exclude-flags = ["arg", "v1", "v2", "duet", "neuro", "christmas", "halloween", "quarantine", "zvv_quarantine"]
path = "Duplicates_v3_Evil"
mp3gain = false
include-type = "and"

[[Presets]]
name = "ZVV Duplicates v3 Duets"
group = "zvv_sort"
include-flags = ["duplicate", "duet", "v3"]
exclude-flags = ["arg", "v1", "v2", "christmas", "halloween", "quarantine", "zvv_quarantine"]
path = "Duplicates_v3_Duets"
mp3gain = false
include-type = "and"

[[Presets]]
name = "ZVV Duplicates v2"
group = "zvv_sort"
include-flags = ["v2", "duplicate"]
exclude-flags = ["arg", "v3", "v1", "christmas", "halloween", "quarantine", "zvv_quarantine"]
path = "Duplicates_v2"
mp3gain = false
include-type = "and"

[[Presets]]
name = "ZVV Duplicates v1"
group = "zvv_sort"
include-flags = ["v1", "duplicate"]
exclude-flags = ["arg", "v3", "v2", "christmas", "halloween", "quarantine", "zvv_quarantine"]
# From root
path = "Duplicates_v1"
mp3gain = false
include-type = "and"

[[Presets]]
name = "ZVV ARG"
group = "zvv_sort"
include-flags = ["arg"]
exclude-flags = []
path = "arg"
mp3gain = false

[[Presets]]
name = "ZVV Christmas Neuro"
group = "zvv_sort"
include-flags = ["christmas", "neuro"]
include-type = "and"
exclude-flags = ["quarantine", "zvv_quarantine", "v1", "v2", "collab", "duet"]
path = "Christmas_Neuro"
mp3gain = false

[[Presets]]
name = "ZVV Christmas Evil"
group = "zvv_sort"
include-flags = ["christmas", "evil"]
include-type = "and"
exclude-flags = ["quarantine", "zvv_quarantine", "v1", "v2", "collab", "duet"]
path = "Christmas_Evil"
mp3gain = false

[[Presets]]
name = "ZVV Christmas Duets"
group = "zvv_sort"
include-flags = ["christmas", "duet"]
include-type = "and"
exclude-flags = ["quarantine", "zvv_quarantine", "v1", "v2", "collab"]
path = "Christmas_Duets"
mp3gain = false

[[Presets]]
name = "ZVV Christmas Collabs"
group = "zvv_sort"
include-flags = ["christmas", "collab"]
include-type = "and"
exclude-flags = ["quarantine", "zvv_quarantine", "v1", "v2"]
path = "Christmas_Collab"
mp3gain = false

[[Presets]]
name = "ZVV Halloween Neuro"
group = "zvv_sort"
include-flags = ["halloween", "neuro"]
include-type = "and"
exclude-flags = ["quarantine", "zvv_quarantine", "v1", "v2", "collab", "duet"]
path = "Halloween_Neuro"
mp3gain = false

[[Presets]]
name = "ZVV Halloween Evil"
group = "zvv_sort"
include-flags = ["halloween", "evil"]
include-type = "and"
exclude-flags = ["quarantine", "zvv_quarantine", "v1", "v2", "collab", "duet"]
path = "Halloween_Evil"
mp3gain = false

[[Presets]]
name = "ZVV Halloween Duets"
group = "zvv_sort"
include-flags = ["halloween", "duet"]
include-type = "and"
exclude-flags = ["quarantine", "zvv_quarantine", "v1", "v2", "collab"]
path = "Halloween_Duets"
mp3gain = false

[[Presets]]
name = "ZVV Halloween Collabs"
group = "zvv_sort"
include-flags = ["halloween", "collab"]
include-type = "and"
exclude-flags = ["quarantine", "zvv_quarantine", "v1", "v2"]
path = "Halloween_Collab"
mp3gain = false

[[Presets]]
name = "ZVV v1 Christmas"
group = "zvv_sort"
include-flags = ["christmas"]
exclude-flags = ["quarantine", "zvv_quarantine", "v2", "v3"]
path = "Christmas_v1"
mp3gain = false

[[Presets]]
name = "ZVV v1 Halloween"
group = "zvv_sort"
include-flags = ["halloween"]
exclude-flags = ["quarantine", "zvv_quarantine", "v2", "v3"]
path = "Halloween_v1"
mp3gain = false

[[Presets]]
name = "ZVV Quarantine"
group = "zvv_sort"
include-flags = ["quarantine", "zvv_quarantine"]
exclude-flags = []
path = "Quarantine"
mp3gain = false

[[Presets]]
name = "ZVV Unused v3"
group = "zvv_sort"
include-flags = ["unused", "v3"]
include-type = "and"
exclude-flags = []
path = "Unused_v3"
mp3gain = false

[[Presets]]
name = "ZVV Unused v2"
group = "zvv_sort"
include-flags = ["unused", "v2"]
include-type = "and"
exclude-flags = []
path = "Unused_v2"
mp3gain = false

[[Presets]]
name = "ZVV Unused v1"
group = "zvv_sort"
include-flags = ["unused", "v1"]
include-type = "and"
exclude-flags = []
path = "Unused_v1"
mp3gain = false
