[project]
name = "Neuro-Songs"
version = "0.1.0"
description = "Formatting Neuro songs to be better in media players"
authors = [{ name = "Zhe_Vlach_Varon", email = "42blah6434@gmail.com" },
           { name = "Matthieu Basset", email = "bassetmatt@gmail.com" }]
dependencies = [
    "connectorx>=0.4.3",
    "loguru>=0.7.3",
    "mutagen>=1.47.0",
    "pandas>=2.3.0",
    "pillow>=11.2.1",
    "polars>=1.30.0",
    "pyarrow>=20.0.0",
    "sqlalchemy>=2.0.41",
    "tqdm>=4.67.1",
    "tinytag>=2.2.0",
    "xxhash>=3.6.0",
]
requires-python = ">=3.11, <3.13"
readme = "README.md"
license-files = ["LICENSE-APACHE", "LICENSE-MIT"]

# WHEN ADDING A COMMAND HERE, run 'pdm install' after for it to be added to path
[project.scripts] # Shortcuts, have a command for main run so that it emulates a "real" run
songs-generate = "neuro.run:generate_songs"
albums-generate = "neuro.run:generate_albums"
update-json = "neuro.run:new_batch_detection"
thumbnails-generate = "neuro.thumbnails:generate_main"
thumbnails-old = "neuro.thumbnails:generate_oldge"
update-db = "neuro.json_to_csv:update_db"
clear-db = "neuro.json_to_csv:clear_db"
# Shouldn't ever need to use this again, was used to update the database after switching from using file hashes to using hashes of just the audio data
update-hashes = "neuro.json_to_csv:update_db_hashes" 
update-filenames = "neuro.json_to_csv:update_db_filenames"
add-special = "neuro.json_to_csv:add_special"
add-comment = "neuro.json_to_csv:add_comment"
db-check = "neuro.checks:all_tests"
inputs-pull = "neuro._shortcuts:inputs_pull"
setlists-pull = "neuro._shortcuts:setlists_pull"
setlists-push = "neuro._shortcuts:setlists_push"
drive-pull = "neuro._shortcuts:drive_pull"
drive-push = "neuro._shortcuts:drive_push"
db-sync = "neuro._shortcuts:dbs_sync"
mp3gain_standalone = "neuro.run:mp3gain_standalone"
setlist-check = "neuro.detection:run_setlist_check"

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pdm]
distribution = true

[dependency-groups]
dev = ["ipykernel>=6.29.5"]

[tool.ruff] # See https://github.com/astral-sh/ruff#configuration
line-length = 120
